"""Parses KML files.

KML files are polygon/route files exported from Google Earth or generated by Planenificator.
"""

import xml.etree.ElementTree as ET
from typing import List, Optional, Tuple


def _get_tag_name(elem) -> str:
  tag = elem.tag
  if '}' in tag:
    return tag.split('}', 1)[1]
  return tag


def parse_kml_route(file_path: str) -> List[Tuple[float, float, Optional[str]]]:
  """
  Parses KML file and extracts list of (lat, lon, name) tuples.
  Supports both individual Placemarks with Point+Name and LineString routes.
  """
  tree = ET.parse(file_path)
  root = tree.getroot()

  placemarks = []
  for elem in root.iter():
    if _get_tag_name(elem) == 'Placemark':
      placemarks.append(elem)

  point_waypoints = []
  for pm in placemarks:
    name = None
    coords_text = None
    has_point = False
    for child in pm.iter():
      tag = _get_tag_name(child)
      if tag == 'name' and child.text and name is None:
        name = child.text.strip()
      elif tag == 'Point':
        has_point = True
      elif tag == 'coordinates' and child.text:
        coords_text = child.text.strip()

    if has_point and coords_text:
      for p in coords_text.split():
        parts = p.split(',')
        if len(parts) >= 2:
          point_waypoints.append((float(parts[1]), float(parts[0]), name))

  if point_waypoints:
    return point_waypoints

  coords_list = []
  for elem in root.iter():
    if _get_tag_name(elem) == 'coordinates' and elem.text:
      for p in elem.text.strip().split():
        parts = p.split(',')
        if len(parts) >= 2:
          coords_list.append((float(parts[1]), float(parts[0]), None))

  return coords_list


def parse_kml_polygon(file_path: str) -> List[Tuple[float, float]]:
  """
  Parses KML file and extracts (lat, lon) coordinate tuples.
  """
  route = parse_kml_route(file_path)
  return [(lat, lon) for lat, lon, _ in route]

