"""Parses KML files.

KML files are polygon/route files exported from Google Earth or generated by Planenificator.
"""

import xml.etree.ElementTree as ET
from typing import List, Optional, Tuple

from planenificator import osm


def parse_kml_route(file_path: str) -> List[Tuple[float, float, Optional[str]]]:
  """
  Parses KML file and extracts list of (lat, lon, name) tuples.
  Supports both individual Placemarks with Point+Name and LineString routes.
  """
  tree = ET.parse(file_path)
  root = tree.getroot()

  all_coords, names = [], []
  for elem in tree.findall('.//{*}Placemark'):
    name = elem.find('{*}name').text
    coords_str = elem.find('.//{*}coordinates').text.split(',')
    coords = float(coords_str[1]), float(coords_str[0])
    if not name:
      name = osm.get_osm_landmark(coords[0], coords[1])
    all_coords.append(coords)
    names.append(name)

  return all_coords, names
